.PHONY: help
help:
	@echo "Targets:"
	@echo "  make dev-up            Start postgres (docker compose)"
	@echo "  make dev-down          Stop postgres"
	@echo "  make dev-ps            Show containers"
	@echo "  make dev-logs          Tail postgres logs"
	@echo "  make db-psql           Open psql (via compose exec)"
	@echo "  make migrate-status    Show migration status"
	@echo "  make migrate-up        Apply migrations"
	@echo "  make api               Run API (loads ENV_FILE)"
	@echo "  make api-log           Run API + tee to /tmp/api.log"
	@echo "  make check             gofmt + test + vet"
	@echo "  make audit             check + rules: no >100 lines + 1 pkg/dir (+ makefiles <=100)"
	@echo "  make sanity            curl /health /v1/health /ga-ada"
	@echo ""
	@echo "Vars:"
	@echo "  ENV_FILE=.env"
	@echo "  COMPOSE_FILE=deploy/docker/docker-compose.dev.yml"
